wip #4
WillDev-Co/books-crud pull request #14
Opened 2023-03-18 15:02 UTC by wiltait

Resolves #3

2023-03-18 16:31 UTC, alesr commented on tempCodeRunnerFile.py
What is this file and why the get books is not here?

2023-03-18 19:47 UTC, wiltait commented on tempCodeRunnerFile.py
No idea. Everything is in the api.py file.

What I've noticed during the bootcamp is that, in every project, this 'temporary file' would be automatically created. Maybe it's a Python thing.

2023-03-19 01:27 UTC, wiltait commented on tempCodeRunnerFile.py
I've looked it up on stackoverflow:

"It indicates that you have selected part of the code snippet and run it.
You can add "code-runner.ignoreSelection": true in the settings.json file to avoid it."

2023-03-19 08:17 UTC, alesr commented on tempCodeRunnerFile.py
If it's part of your vscode or environment in general, it shouldn't go into master. Each developer uses different tools and we don't want all sort of configurations to live here.

2023-03-19 08:18 UTC, alesr commented on api.py
> +@app.get("/hello")
This one was just for you to learn how to create endpoints. You remove it now.

2023-03-19 08:21 UTC, alesr requested changes
Tests are missing.

https://docs.python.org/3/library/unittest.html

https://fastapi.tiangolo.com/tutorial/testing/

2023-03-19 08:24 UTC, alesr commented on __pycache__/api.cpython-311.pyc
This directory shouldn't be pushed to the repository.

https://towardsdatascience.com/pycache-python-991424aabad8

https://sebastiandedeyne.com/setting-up-a-global-gitignore-file/

2023-04-20 13:27 UTC, closed without merging